# Generated by Django 5.1.2 on 2025-08-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Syrup', 'Syrup'), ('Powder', 'Powder'), ('Topping', 'Topping'), ('Tea', 'Tea')], max_length=10)),
                ('quantity_box', models.IntegerField(default=0)),
                ('current_individual_stock', models.IntegerField(default=0)),
                ('current_box_stock', models.IntegerField(default=0)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity_box', models.IntegerField(default=0)),
                ('current_individual_stock', models.IntegerField(default=0)),
                ('current_box_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
