# Generated by Django 5.1.2 on 2025-08-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientID', models.AutoField(db_column='ingredientID', primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(db_column='ingredient_name', max_length=50)),
                ('type', models.CharField(choices=[('Syrup', 'Syrup'), ('Powder', 'Powder'), ('Topping', 'Topping'), ('Tea', 'Tea')], max_length=10)),
                ('quantity_box', models.IntegerField(default=0)),
                ('current_individual_stock', models.IntegerField(default=0)),
                ('current_box_stock', models.IntegerField(default=0)),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('miscellaneousID', models.AutoField(db_column='miscellaneousID', primary_key=True, serialize=False)),
                ('miscellaneous_name', models.CharField(db_column='miscellaneous_name', max_length=50)),
                ('quantity_box', models.IntegerField(default=0)),
                ('current_individual_stock', models.IntegerField(default=0)),
                ('current_box_stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'miscellaneous',
            },
        ),
    ]
