# Generated by Django 5.1.2 on 2025-08-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ingredient_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='test_field',
        ),
    ]
