# Generated by Django 5.1.2 on 2025-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_ingredient_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_column='ingredientName', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='name',
            field=models.CharField(db_column='miscellaneous_name', max_length=50),
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredients',
        ),
        migrations.AlterModelTable(
            name='miscellaneous',
            table='miscellaneous',
        ),
    ]
